"use client";

import { modelEpisodes, modelQuality, groupEpisodes, teamQualityContribution, type ModelProgramId, type ModelView, type ModeledQuality } from "@/data/synthetic/modelProgram";
import { measureSources } from "@/data/reference/programQualityMeasures";
import ProgramQualityMeasures from "./ProgramQualityMeasures";
import { action, dollars, panel } from "./ModelCostDashboard";

const resultText = (value: number, measure: ModeledQuality) => `${value.toFixed(measure.unit === "index" ? 2 : 1)}${measure.unit === "%" ? "%" : measure.unit === "points" ? " pts" : ""}`;
const onTarget = (measure: ModeledQuality) => measure.lower ? measure.current <= measure.target : measure.current >= measure.target;

function QualityTrend({ measure }: { measure: ModeledQuality }) {
  const values = measure.history;
  const span = Math.max(...values) - Math.min(...values);
  const min = Math.min(...values) - span * 0.15;
  const max = Math.max(...values) + span * 0.15;
  const y = (value: number) => 32 - (value - min) / Math.max(0.01, max - min) * 28;
  const delta = values[values.length - 1] - values[0];
  const improving = measure.lower ? delta < 0 : delta > 0;
  return <div className="w-32"><svg viewBox="0 0 128 38" className="h-10 w-32" role="img" aria-label={`Modeled trend from ${resultText(values[0], measure)} to ${resultText(measure.current, measure)}`}><title>{values.map(value => resultText(value, measure)).join(" → ")}</title><polyline fill="none" stroke={improving ? "#207b80" : "#b45309"} strokeWidth="2.5" points={values.map((value, i) => `${4 + i * 24},${y(value)}`).join(" ")} /><circle cx="124" cy={y(measure.current)} r="3" fill="#207b80" /></svg><p className={`text-[10px] font-semibold ${improving ? "text-emerald-700" : "text-amber-700"}`}>{delta > 0 ? "+" : ""}{delta.toFixed(measure.unit === "index" ? 2 : 1)} {measure.unit === "%" ? "pp" : measure.unit === "index" ? "index" : "pts"} · {improving ? "Improving" : "Declining"}</p></div>;
}

export default function ModelQualityDashboard({ program, state, change }: { program: ModelProgramId; state: ModelView; change: (patch: Record<string, string>) => void }) {
  const team = program === "cms-team";
  const measures = modelQuality(program).filter(measure => state.cohort === "all" || measure.definition.group === state.cohort);
  const selected = measures.find(measure => measure.key === state.measure) ?? measures[0];
  const contributions = teamQualityContribution();
  const contribution = contributions.find(item => item.key === selected.key);
  const isPro = selected.key === "team-pro-2026";
  const isSafety = selected.key === "team-psi90";
  const cohort = modelEpisodes[program].filter(e => team ? !isPro || e.type === "Lower extremity joint replacement" : e.type === selected.definition.group);
  const providers = groupEpisodes(cohort, "attending");
  const selectedProvider = providers.find(row => row.name === state.provider);
  const indicator = isPro ? "Follow-up PRO forms" : isSafety ? "Safety events flagged" : "Observed readmissions";
  const providerRate = (index: number) => selected.current + (index - 1.5) * (selected.unit === "points" ? 0.4 : 2);
  const providerResult = (row: typeof providers[number], index: number) => {
    const count = row.records.filter(e => isPro ? e.proComplete : isSafety ? e.safetyEvent : e.readmitted).length;
    return team ? { value: `${count} / ${row.count}`, rate: `${(count / row.count * 100).toFixed(1)}%` } : { value: resultText(providerRate(index), selected), rate: `${row.count} eligible episodes` };
  };
  return <div id="program-quality-measures" className="space-y-4 scroll-mt-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-xl font-bold text-slate-900">Quality measures</h3><p className="mt-1 text-xs text-slate-500">{team ? "Hospital-level performance · PY 2026 measure set" : "Specialist performance · PY 2027 scenario"} · Modeled results and internal targets</p></div>{!team && <label className="text-xs font-semibold text-slate-600">Cohort<select className="ml-2 rounded-md border border-slate-300 bg-white p-2" value={state.cohort} onChange={e => change({ qualityCohort: e.target.value, qualityMeasure: "", qualityProvider: "" })}><option value="all">All cohorts</option><option>Heart failure</option><option>Low back pain</option></select></label>}</div>
    <section className={`${panel} overflow-x-auto`}><table className="w-full min-w-[830px] text-left text-xs"><thead className="border-b border-slate-200 text-[10px] uppercase tracking-wide text-slate-500"><tr><th className="pb-3">Measure</th><th className="pb-3">Current</th><th className="pb-3">Internal target</th><th className="pb-3">Apr–Sep trend</th>{team && <th className="pb-3">CQS contribution</th>}<th className="pb-3"><span className="sr-only">Detail</span></th></tr></thead><tbody className="divide-y divide-slate-100">{measures.map(measure => <tr key={measure.key} className={selected.key === measure.key ? "bg-[#f0f7f5]" : "hover:bg-slate-50"}><td className="max-w-[380px] py-4 pl-2 pr-4"><button type="button" aria-pressed={selected.key === measure.key} className="text-left font-bold text-[#176b75] hover:underline" onClick={() => change({ qualityMeasure: measure.key, qualityProvider: "" })}>{measure.label}</button><p className="mt-1 text-[10px] text-slate-500">{measure.definition.id}{!team && ` · ${measure.definition.group}`}</p><p className="mt-1 text-[10px] text-slate-500">{measure.lower ? "Lower" : "Higher"} is better{measure.unit === "index" ? " · risk-adjusted index" : ""}</p></td><td className="py-4 pr-4 text-base font-bold tabular-nums text-slate-900">{resultText(measure.current, measure)}</td><td className="py-4 pr-4"><p className="font-semibold text-slate-700">{measure.lower ? "≤" : "≥"}{resultText(measure.target, measure)}</p><p className={`mt-1 text-[10px] ${onTarget(measure) ? "text-emerald-700" : "text-amber-700"}`}>{onTarget(measure) ? "Target met" : "Off target"}</p></td><td className="py-4 pr-4"><QualityTrend measure={measure} /></td>{team && <td className="py-4 pr-4"><p className="font-semibold text-slate-800">{contributions.find(item => item.key === measure.key)?.contribution.toFixed(1)} pts</p><p className="mt-1 text-[10px] text-slate-500">{((contributions.find(item => item.key === measure.key)?.weight ?? 0) * 100).toFixed(1)}% weight</p></td>}<td className="py-4 pr-2"><button type="button" className={action} onClick={() => { change({ qualityMeasure: measure.key, qualityProvider: "" }); document.getElementById("measure-performance-detail")?.scrollIntoView({ behavior: "smooth", block: "start" }); }} aria-label={`View ${measure.label} performance`}>View →</button></td></tr>)}</tbody></table><p className="mt-3 text-[11px] text-slate-500">Trends use a separate scale for each measure. {team ? "Scaled scores are illustrative national percentiles; raw results alone do not determine CQS." : "Future-year scenario; no submitted ASM results."}</p></section>
    <section id="measure-performance-detail" className={`${panel} scroll-mt-4`}><div className="flex flex-wrap items-start justify-between gap-4"><div className="max-w-3xl"><p className="text-[10px] font-bold uppercase tracking-wide text-[#176b75]">{selected.definition.id}</p><h4 className="mt-1 text-base font-bold text-slate-900">{selected.definition.name}</h4><p className="mt-2 text-xs leading-5 text-slate-500">{selected.definition.collection} · {selected.definition.applicability}</p><p className="text-xs leading-5 text-slate-500">Published measurement period: {selected.definition.period}</p></div><a className={action} href={selected.definition.source} target="_blank" rel="noreferrer">Specification ↗</a></div>
      {contribution ? <div className="mt-4 grid grid-cols-2 gap-4 rounded-lg bg-slate-50 p-4 md:grid-cols-4">{[["Scaled measure score", `${selected.scaled} / 100`], ["Applicable episode volume", selected.volume?.toLocaleString()], ["Normalized weight", `${(contribution.weight * 100).toFixed(1)}%`], ["CQS contribution", `${contribution.contribution.toFixed(1)} points`]].map(([label, value]) => <div key={label}><p className="text-[11px] text-slate-500">{label}</p><p className="mt-1 text-lg font-bold text-slate-900">{value}</p></div>)}</div> : <p className="mt-3 text-xs text-slate-600">{selected.definition.note ?? "Apply the cohort and collection-specific measure specification."}</p>}
    </section>
    <section id="provider-performance" className={`${panel} scroll-mt-4`}><div className="flex flex-wrap items-end justify-between gap-3"><div><h4 className="text-base font-bold text-slate-900">Provider performance</h4><p className="mt-1 text-xs text-slate-500">{team ? `Jan–Sep 2026 · ${indicator} · Internal episode attribution` : `${selected.label} · ${selected.definition.group} cohort`}</p></div><span className="text-[11px] text-slate-500">{providers.length} providers · {cohort.length} episodes</span></div>{team && <p className="mt-2 text-[11px] leading-5 text-slate-500">Provider indicators support investigation. They are not the hospital’s risk-adjusted CMS measure scores.{isPro ? " Form completion is not the PRO outcome result." : isSafety ? " Flagged events are not a calculated PSI 90 index." : " Observed episode readmissions are not the hospital-wide HWR rate."}</p>}
      <div className="mt-3 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{["Provider", "Episodes", team ? indicator : "Measure result", team ? "Observed rate" : "Cohort", "Avg episode spend", "Cost difference"].map(label => <th key={label} className="p-2.5">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{providers.map((row, index) => <tr key={row.name} className={row.name === state.provider ? "bg-teal-50" : "hover:bg-slate-50"}><td className="p-2.5"><button type="button" className="font-semibold text-[#176b75] hover:underline" onClick={() => change({ qualityProvider: row.name })}>{row.name} →</button></td><td className="p-2.5">{row.count}</td><td className="p-2.5 font-semibold">{providerResult(row, index).value}</td><td className="p-2.5">{providerResult(row, index).rate}</td><td className="p-2.5">{dollars(row.average)}</td><td className={`p-2.5 font-semibold ${row.difference >= 0 ? "text-emerald-700" : "text-amber-700"}`}>{dollars(row.difference)}</td></tr>)}</tbody></table></div>
      {selectedProvider && <div className="mt-4 rounded-lg border border-[#b5d1ca] bg-[#f5fbf8] p-4" role="region" aria-label="Provider detail"><div className="flex flex-wrap items-start justify-between gap-3"><div><h5 className="font-bold text-slate-900">{selectedProvider.name}</h5><p className="mt-1 text-xs text-slate-600">{selectedProvider.count} episodes · {selectedProvider.better} below cost target · {providerResult(selectedProvider, providers.indexOf(selectedProvider)).value} {team ? indicator.toLowerCase() : "measure result"}</p></div><button type="button" className={action} onClick={() => change({ section: "cost", costTab: "episodes", attending: selectedProvider.name, episodeType: isPro ? "Lower extremity joint replacement" : team ? "all" : selected.definition.group, episodeSubtype: "all", facility: "all", operating: "all", range: "all", better: "all", death: "all", episodePage: "", episode: "" })}>View provider episodes →</button></div><p className="mt-3 text-xs text-slate-500">{team ? isPro ? "Review missing follow-up forms and link them to the eligible surgical cohort." : isSafety ? "Review flagged inpatient safety events and supporting documentation." : "Review readmission episodes, discharge follow-up and post-acute utilization." : "Review the specialist’s measure cohort and related episode costs."}</p></div>}
    </section>
    <details className={panel}><summary className="cursor-pointer text-sm font-semibold text-[#176b75]">Published measure requirements</summary><div className="mt-4"><ProgramQualityMeasures programId={program} idPrefix="published-quality" /></div></details>
    <p className="text-[11px] text-slate-500">{team ? <a className="underline" href={measureSources.teamScoring} target="_blank" rel="noreferrer">CMS quality scoring methodology ↗</a> : <a className="underline" href={measureSources.asm} target="_blank" rel="noreferrer">CMS ASM performance categories ↗</a>} · Modeled performance</p>
  </div>;
}
