"use client";

import { useEffect, useState } from "react";
import { episodeStats, modelEpisodes, modelQuality, modelViewKeys, parseModelView, teamQualityContribution, teamReconciliation, type ModelProgramId } from "@/data/synthetic/modelProgram";
import { measureSources } from "@/data/reference/programQualityMeasures";
import ModelCostDashboard, { action, dollars, panel } from "./ModelCostDashboard";
import ProgramPerformanceOverview from "./ProgramPerformanceOverview";
import { hdiObligations } from "@/data/synthetic/healthIntelligenceObligations";
import ModelQualityDashboard from "./ModelQualityDashboard";

export default function ModelProgramWorkspace({ program, onBack }: { program: ModelProgramId; onBack: () => void }) {
  const [state, setState] = useState(() => parseModelView(new URLSearchParams(), program));
  useEffect(() => {
    const sync = () => setState(parseModelView(new URLSearchParams(window.location.search), program));
    sync();
    window.addEventListener("popstate", sync);
    return () => window.removeEventListener("popstate", sync);
  }, [program]);
  const change = (patch: Record<string, string>) => {
    const url = new URL(window.location.href);
    for (const [key, value] of Object.entries(patch)) {
      if (!modelViewKeys.includes(key)) continue;
      if (value && value !== "all") url.searchParams.set(key, value); else url.searchParams.delete(key);
    }
    window.history.pushState(null, "", url);
    setState(parseModelView(url.searchParams, program));
  };
  const team = program === "cms-team";
  const measures = modelQuality(program);
  const cost = episodeStats(modelEpisodes[program]);
  const score = teamReconciliation();
  const offTarget = measures.filter(m => m.lower ? m.current > m.target : m.current < m.target).length;
  const moneyShort = (value: number) => `$${(value / 1_000_000).toFixed(2)}M`;
  return <section className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#28737a]">Program</p><h2 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">{team ? "CMS TEAM" : "Ambulatory Specialty Model"}</h2><p className="mt-2 text-xs text-slate-500">{team ? "Hyperion Medical Center · Performance year 2026" : "Heart failure & low back pain · Performance year 2027 scenario"}</p></div><div className="flex flex-wrap items-center gap-3"><span className="rounded-full bg-slate-100 px-3 py-1.5 text-[11px] font-semibold text-slate-600">Modeled performance</span><button type="button" onClick={onBack} className={action}>← Back to portfolio</button></div></div>
    <ProgramPerformanceOverview obligation={hdiObligations.find(item => item.id === program)!} onQuality={() => change({ section: "quality" })} onModelSection={section => change({ section })} />
    <nav aria-label="Program sections" className="flex gap-1 border-b border-slate-200">{([ ["overview", "Overview"], ["quality", "Quality"], ["cost", "Cost"] ] as const).map(([section, label]) => <button key={section} type="button" aria-current={state.section === section ? "page" : undefined} onClick={() => change({ section })} className={`border-b-2 px-5 py-3 text-sm font-semibold ${state.section === section ? "border-[#207b80] text-[#176b75]" : "border-transparent text-slate-500 hover:text-slate-900"}`}>{label}</button>)}</nav>
    {state.section === "quality" ? <ModelQualityDashboard program={program} state={state} change={change} /> : state.section === "cost" ? <ModelCostDashboard program={program} state={state} change={change} /> : <>
      <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[["Episodes", cost.count.toLocaleString()], [team ? "Episode types" : "Clinical cohorts", team ? "5" : "2"], ["Quality measures", String(measures.length)], ["Providers in example", "4"]].map(([label, value]) => <div key={label} className="rounded-lg border border-slate-200 bg-white px-4 py-3"><p className="text-[11px] text-slate-500">{label}</p><p className="mt-1 text-xl font-bold text-slate-900">{value}</p></div>)}</div>
      <div className="grid gap-4 xl:grid-cols-2"><section className={`${panel} flex flex-col`}><div className="flex items-center justify-between"><h3 className="text-lg font-bold text-slate-900">Quality</h3><span className="rounded-full bg-amber-50 px-2.5 py-1 text-[10px] font-semibold text-amber-700">{offTarget} off internal target</span></div><div className="my-4 flex items-end justify-between gap-4"><div><p className="text-4xl font-bold tracking-tight text-[#176b75]">{team ? score.cqs.toFixed(1) : `${measures.length - offTarget} / ${measures.length}`}<span className="ml-1 text-sm font-normal text-slate-500">{team ? "/ 100" : "on target"}</span></p><p className="mt-1 text-xs text-slate-500">{team ? "Composite quality score" : "Modeled measure performance"}</p></div>{team && <div className="text-right"><p className="text-xl font-bold text-amber-700">−{dollars(score.reduction)}</p><p className="mt-1 text-[11px] text-slate-500">Quality adjustment</p></div>}</div>
        <div className="mb-5 divide-y divide-slate-100 border-y border-slate-100">{(team ? measures : measures.filter(m => ["asm-492", "asm-236", "asm-220"].includes(m.key))).map(measure => <button key={measure.key} type="button" onClick={() => change({ section: "quality", qualityMeasure: measure.key, qualityCohort: "", qualityProvider: "" })} className="flex w-full items-center justify-between gap-3 py-3 text-left text-xs hover:text-[#176b75]"><span><span className="font-semibold text-slate-700">{measure.label}</span><span className="mt-1 block text-[10px] text-slate-500">{measure.definition.id}</span></span><span className="shrink-0 text-right font-semibold text-[#176b75]">{team ? `${teamQualityContribution().find(m => m.key === measure.key)?.contribution.toFixed(1)} CQS pts` : `${measure.current}${measure.unit === "%" ? "%" : " pts"}`} →</span></button>)}</div>
        <div className="mt-auto flex flex-wrap gap-2"><button type="button" onClick={() => change({ section: "quality" })} className="rounded-lg bg-[#285954] px-4 py-2.5 text-xs font-semibold text-white hover:bg-[#1f4b47]">View quality →</button><button type="button" className={action} onClick={() => { change({ section: "quality" }); requestAnimationFrame(() => document.getElementById("provider-performance")?.scrollIntoView({ behavior: "smooth" })); }}>Provider performance →</button></div>
      </section>
      <section className={`${panel} flex flex-col`}><div className="flex items-center justify-between"><h3 className="text-lg font-bold text-slate-900">Cost</h3><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-semibold text-emerald-700">{cost.betterRate.toFixed(1)}% below target</span></div><div className="my-4"><p className="text-4xl font-bold tracking-tight text-[#176b75]">+{dollars(cost.difference)}</p><p className="mt-1 text-xs text-slate-500">{team ? "Reconciliation before quality adjustment" : "Modeled difference from cost target"}</p></div><div className="mb-4 grid grid-cols-2 gap-4 rounded-lg bg-slate-50 p-4"><div><p className="text-[11px] text-slate-500">Total spend</p><p className="mt-1 text-xl font-bold text-slate-800">{moneyShort(cost.spend)}</p><p className="mt-1 text-[10px] text-slate-500">{dollars(cost.average)} per episode</p></div><div><p className="text-[11px] text-slate-500">Total target</p><p className="mt-1 text-xl font-bold text-slate-800">{moneyShort(cost.target)}</p><p className="mt-1 text-[10px] text-slate-500">{dollars(cost.averageTarget)} per episode</p></div></div><p className="mb-5 text-xs leading-5 text-slate-500">{team ? "732 episodes across CABG, major bowel, hip/femur fracture, joint replacement and spinal fusion. Inspect spend by episode type, subtype and provider." : "Heart Failure (COST_HF_1) and Low Back Pain (COST_LBP_1). Compare modeled episode costs by condition and specialist."}</p><div className="mt-auto"><button type="button" onClick={() => change({ section: "cost", costTab: "summary" })} className="rounded-lg bg-[#285954] px-4 py-2.5 text-xs font-semibold text-white hover:bg-[#1f4b47]">View cost dashboard →</button></div></section></div>
      {team ? <section className={`${panel} bg-[#f7faf9]`}><h3 className="text-base font-bold text-slate-900">Reconciliation estimate</h3><div className="mt-4 grid gap-4 sm:grid-cols-3"><div><p className="text-xs text-slate-500">Cost contribution</p><p className="mt-1 text-2xl font-bold text-slate-900">{dollars(score.gross)}</p><p className="mt-1 text-[11px] text-slate-500">Target less episode spending</p></div><div><p className="text-xs text-slate-500">Quality adjustment</p><p className="mt-1 text-2xl font-bold text-amber-700">−{dollars(score.reduction)}</p><p className="mt-1 text-[11px] text-slate-500">{(score.reductionRate * 100).toFixed(1)}% reduction at {score.cqs.toFixed(0)} CQS</p></div><div className="border-l-2 border-[#b5d1ca] pl-4"><p className="text-xs font-semibold text-[#176b75]">After quality adjustment</p><p className="mt-1 text-2xl font-bold text-emerald-700">{dollars(score.net)}</p><p className="mt-1 text-[11px] text-slate-500">Before other CMS adjustments</p></div></div><details className="mt-4 border-t border-slate-200 pt-3 text-xs text-slate-500"><summary className="cursor-pointer font-semibold text-[#176b75]">Calculation</summary><p className="mt-2 leading-5">Positive reconciliation example: quality reduction = reconciliation × 10% × (1 − CQS / 100). CQS sums each scaled quality score weighted by applicable episode volume. This scenario does not model the full settlement process.</p><a href={measureSources.teamScoring} target="_blank" rel="noreferrer" className="mt-2 inline-block underline">CMS quality scoring methodology ↗</a></details></section> : <section className={panel}><h3 className="text-sm font-bold text-slate-900">Other performance categories</h3><div className="mt-3 grid gap-3 md:grid-cols-2"><details className="rounded-lg border border-slate-200 p-3"><summary className="cursor-pointer text-xs font-semibold text-[#176b75]">Improvement activities · Preparation</summary><p className="mt-3 text-xs leading-5 text-slate-600">IA-1: primary care connection and HRSN screening. IA-2: collaborative care arrangements with primary care. Retain evidence and attest to completion.</p></details><details className="rounded-lg border border-slate-200 p-3"><summary className="cursor-pointer text-xs font-semibold text-[#176b75]">Promoting interoperability · Preparation</summary><p className="mt-3 text-xs leading-5 text-slate-600">Confirm the CEHRT ID, PI measure reporting and required attestations for the reporting group.</p></details></div><p className="mt-3 text-[11px] text-slate-500">ASM has four performance categories. The examples above do not calculate a final ASM score or payment adjustment. <a href={measureSources.asm} target="_blank" rel="noreferrer" className="underline">CMS requirements ↗</a></p></section>}
    </>}
  </section>;
}
