"use client";

import { episodeStats, filterEpisodes, groupEpisodes, modelEpisodes, type CostFilters, type Episode, type ModelProgramId, type ModelView } from "@/data/synthetic/modelProgram";

export const dollars = (value: number) => value.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
export const panel = "rounded-xl border border-slate-200 bg-white p-5 shadow-sm";
export const action = "rounded-lg border border-[#b5d1ca] bg-white px-3 py-2 text-xs font-semibold text-[#176b75] hover:bg-[#eff7f4] focus-visible:outline-2 focus-visible:outline-[#176b75]";
export const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"];
type Change = (patch: Record<string, string>) => void;

function Stat({ label, value, detail }: { label: string; value: string; detail?: string }) {
  return <div><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold tabular-nums text-slate-900">{value}</p>{detail && <p className="mt-1 text-[11px] text-slate-500">{detail}</p>}</div>;
}

function CostBars({ title, rows, kind, onSelect }: { title: string; rows: ReturnType<typeof groupEpisodes>; kind: "count" | "spend"; onSelect: (name: string) => void }) {
  const max = Math.max(1, ...rows.map(row => kind === "count" ? row.count : row.average));
  return <section className={panel}><h4 className="text-sm font-bold text-slate-900">{title}</h4><div className="mt-2 flex gap-4 text-[10px] text-slate-500">{kind === "count" ? <><span><i className="mr-1 inline-block h-2 w-2 rounded-sm bg-[#207b80]" />Below target</span><span><i className="mr-1 inline-block h-2 w-2 rounded-sm bg-[#e49a49]" />At / above target</span></> : <span>Average total spend per episode</span>}</div>
    <div className="mt-4 space-y-3">{rows.map(row => <button key={row.name} type="button" onClick={() => onSelect(row.name)} className="group grid w-full grid-cols-[minmax(120px,40%)_1fr_65px] items-center gap-3 rounded-md text-left focus-visible:outline-2 focus-visible:outline-[#176b75]" aria-label={`Filter ${row.name}`} title={kind === "count" ? `${row.better} below target; ${row.count - row.better} at or above target` : dollars(row.average)}><span className="text-[11px] leading-4 text-slate-600 group-hover:text-[#176b75] group-hover:underline">{row.name}</span><span className="flex h-5 overflow-hidden rounded-sm bg-slate-50" aria-hidden="true">{kind === "count" ? <><span className="bg-[#207b80]" style={{ width: `${row.better / max * 100}%` }} /><span className="bg-[#e49a49]" style={{ width: `${(row.count - row.better) / max * 100}%` }} /></> : <span className="bg-[#91bb80]" style={{ width: `${row.average / max * 100}%` }} />}</span><span className="text-right text-[11px] font-semibold tabular-nums text-slate-700">{kind === "count" ? row.count : dollars(row.average)}</span></button>)}</div>
    <p className="mt-4 text-[10px] text-slate-400">{kind === "count" ? "Episode count" : "USD"} · Select a bar to filter</p>
  </section>;
}

function CostTrend({ episodes, team }: { episodes: Episode[]; team: boolean }) {
  const rows = groupEpisodes(episodes, "month").sort((a, b) => Number(a.name) - Number(b.name));
  const all = rows.flatMap(row => [row.average, row.averageTarget]);
  const min = Math.max(0, Math.floor((Math.min(...all) - 1000) / 1000) * 1000);
  const max = Math.ceil((Math.max(...all) + 1000) / 1000) * 1000;
  const y = (value: number) => 190 - (value - min) / Math.max(1, max - min) * 160;
  const x = (index: number) => 76 + index / Math.max(1, rows.length - 1) * 670;
  return <section className={panel}><h4 className="text-sm font-bold text-slate-900">Average spend and target</h4><p className="mt-1 text-xs text-slate-500">By {team ? "anchor" : "episode"} month · USD · Axis adjusted to the selected range</p><svg viewBox="0 0 810 235" className="mt-3 h-60 w-full" role="img" aria-label="Monthly average spend and target"><title>Monthly average spend and target; exact values in the table below</title>{[min, (min + max) / 2, max].map(value => <g key={value}><line x1="76" x2="746" y1={y(value)} y2={y(value)} stroke="#e2e8f0" /><text x="66" y={y(value) + 4} textAnchor="end" fontSize="11" fill="#64748b">{dollars(value)}</text></g>)}<polyline fill="none" stroke="#94a3b8" strokeDasharray="5 4" strokeWidth="2" points={rows.map((row, i) => `${x(i)},${y(row.averageTarget)}`).join(" ")} /><polyline fill="none" stroke="#207b80" strokeWidth="3" points={rows.map((row, i) => `${x(i)},${y(row.average)}`).join(" ")} />{rows.map((row, i) => <g key={row.name}><circle cx={x(i)} cy={y(row.average)} r="4" fill="#207b80" /><text x={x(i)} y="220" textAnchor="middle" fontSize="11" fill="#64748b">{months[Number(row.name) - 1]}</text></g>)}</svg><p className="text-xs text-slate-500"><span className="font-semibold text-[#207b80]">Solid: actual spend</span> · Dashed: target</p>
    <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{["Month", "Episodes", "Avg spend", "Avg target", "Difference"].map(label => <th key={label} className="p-2">{label}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row.name} className="border-b border-slate-100"><td className="p-2">{months[Number(row.name) - 1]}</td><td className="p-2">{row.count}</td><td className="p-2">{dollars(row.average)}</td><td className="p-2">{dollars(row.averageTarget)}</td><td className="p-2">{dollars(row.averageTarget - row.average)}</td></tr>)}</tbody></table></div>
  </section>;
}

function EpisodeTable({ episodes, state, change, team }: { episodes: Episode[]; state: ModelView; change: Change; team: boolean }) {
  const selected = episodes.find(e => e.id === state.episode);
  const pageCount = Math.max(1, Math.ceil(episodes.length / 15));
  return <section className={panel}><div className="flex items-center justify-between gap-3"><h4 className="text-sm font-bold text-slate-900">Episode details</h4><span className="text-xs text-slate-500">{episodes.length} episodes</span></div>
    {selected && <div className="my-4 rounded-lg border border-[#b5d1ca] bg-[#f5fbf8] p-4" role="region" aria-label={`${selected.id} detail`}><div className="flex justify-between gap-3"><div><p className="font-bold text-slate-900">{selected.id} · {selected.type}</p><p className="mt-1 text-xs text-slate-500">{selected.facility} · {selected.attending} · {months[selected.month - 1]} {team ? 2026 : 2027}</p></div><button type="button" className={action} onClick={() => change({ episode: "" })}>Close detail</button></div><div className="mt-4 grid grid-cols-2 gap-4 md:grid-cols-4"><Stat label="Total spend" value={dollars(selected.spend)} /><Stat label={team ? "Anchor spend" : "Target"} value={dollars(team ? selected.anchor : selected.target)} /><Stat label={team ? "Post-anchor spend" : "Difference"} value={dollars(team ? selected.spend - selected.anchor : selected.target - selected.spend)} /><Stat label="Status" value={selected.spend < selected.target ? "Below target" : "Above target"} /></div><p className="mt-3 text-xs text-slate-500">Synthetic episode · {selected.subtype} · {team ? selected.died ? "Death after discharge recorded" : "No death after discharge recorded" : "Attributed specialist episode"}</p></div>}
    <div className="mt-3 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{["Episode", team ? "Type / subtype" : "Condition / practice", team ? "Attending provider" : "Specialist", team ? "Anchor month" : "Episode month", "Total spend", "Target", "Difference"].map(label => <th key={label} className="p-2.5">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{episodes.slice((state.page - 1) * 15, state.page * 15).map(e => <tr key={e.id} className={e.id === selected?.id ? "bg-teal-50" : "hover:bg-slate-50"}><td className="p-2.5"><button type="button" className="font-semibold text-[#176b75] underline" onClick={() => change({ episode: e.id })}>{e.id}</button></td><td className="p-2.5"><p>{e.type}</p><p className="mt-1 text-[10px] text-slate-500">{e.subtype}</p></td><td className="p-2.5">{e.attending}</td><td className="p-2.5">{months[e.month - 1]}</td><td className="p-2.5 tabular-nums">{dollars(e.spend)}</td><td className="p-2.5 tabular-nums">{dollars(e.target)}</td><td className={`p-2.5 font-semibold tabular-nums ${e.target >= e.spend ? "text-emerald-700" : "text-amber-700"}`}>{dollars(e.target - e.spend)}</td></tr>)}</tbody></table></div>
    <div className="mt-4 flex items-center justify-between"><span className="text-xs text-slate-500">Page {state.page} of {pageCount}</span><div className="flex gap-2"><button type="button" disabled={state.page <= 1} onClick={() => change({ episodePage: String(state.page - 1), episode: "" })} className={`${action} disabled:opacity-40`}>Previous</button><button type="button" disabled={state.page >= pageCount} onClick={() => change({ episodePage: String(state.page + 1), episode: "" })} className={`${action} disabled:opacity-40`}>Next</button></div></div>
  </section>;
}

export default function ModelCostDashboard({ program, state, change }: { program: ModelProgramId; state: ModelView; change: Change }) {
  const team = program === "cms-team";
  const all = modelEpisodes[program];
  const episodes = filterEpisodes(all, state.filters);
  const stats = episodeStats(episodes);
  const filter = (key: keyof CostFilters, value: string) => change({ [key]: value, episodePage: "", episode: "", ...(key === "episodeType" ? { episodeSubtype: "all" } : {}) });
  const options = (key: "facility" | "type" | "subtype" | "attending" | "operating") => [...new Set(all.filter(e => key !== "subtype" || state.filters.episodeType === "all" || e.type === state.filters.episodeType).map(e => e[key]))].map(value => ({ value, label: value }));
  const selectors: { key: keyof CostFilters; label: string; options: { value: string; label: string }[] }[] = [
    { key: "facility", label: team ? "Facility" : "Organization", options: options("facility") },
    { key: "episodeType", label: team ? "Episode type" : "Condition", options: options("type") },
    { key: "episodeSubtype", label: team ? "Episode subtype" : "Practice", options: options("subtype") },
    { key: "range", label: team ? "Anchor date range" : "Episode date range", options: [{ value: "1", label: "Jan–Mar" }, { value: "2", label: "Apr–Jun" }, { value: "3", label: "Jul–Sep" }] },
    { key: "attending", label: team ? "Attending provider" : "Attributed specialist", options: options("attending") },
    ...(team ? [{ key: "operating" as const, label: "Operating provider", options: options("operating") }] : []),
    { key: "better", label: "Below target", options: [{ value: "yes", label: "Yes" }, { value: "no", label: "No" }] },
    ...(team ? [{ key: "death" as const, label: "Death after discharge", options: [{ value: "yes", label: "Yes" }, { value: "no", label: "No" }] }] : []),
  ];
  const active = Object.values(state.filters).some(value => value !== "all");
  return <div className="space-y-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-xl font-bold text-slate-900">{team ? "Episode costs" : "Cost performance"}</h3><p className="mt-1 text-xs text-slate-500">{team ? "Jan–Sep 2026 · Inpatient example cohort · Anchor + 30-day post-discharge spend" : "PY 2027 scenario · Heart failure and low back pain · Claims-based cost measures"}</p></div>{active && <button type="button" className={action} onClick={() => change(Object.fromEntries([...Object.keys(state.filters).map(key => [key, ""]), ["episodePage", ""], ["episode", ""]]))}>Reset filters</button>}</div>
    {!team && <div className="rounded-lg bg-[#edf5f3] p-3 text-xs text-slate-600"><span className="font-semibold">COST_HF_1 · COST_LBP_1</span> · Cost measures are calculated by CMS from claims. Values and targets here are modeled; they are not CMS risk-adjusted cost scores.</div>}
    <div className="grid gap-3 rounded-xl border border-slate-200 bg-[#edf0f2] p-4 sm:grid-cols-2 xl:grid-cols-4">{selectors.map(item => <label key={item.key} className="text-[11px] font-semibold text-slate-600">{item.label}<select value={state.filters[item.key]} onChange={e => filter(item.key, e.target.value)} className="mt-1.5 block w-full rounded-md border border-slate-300 bg-white p-2 text-xs font-normal text-slate-800"><option value="all">{item.key === "range" ? "Jan–Sep · Full range" : "All"}</option>{item.options.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>)}</div>
    <div className={`${panel} grid grid-cols-2 gap-x-6 gap-y-6 xl:grid-cols-4`} aria-live="polite"><Stat label="Episodes" value={stats.count.toLocaleString()} /><Stat label="Episodes below target" value={stats.better.toLocaleString()} /><Stat label="Below target" value={stats.count ? `${stats.betterRate.toFixed(1)}%` : "—"} /><Stat label="Avg difference from target" value={stats.count ? dollars(stats.difference / stats.count) : "—"} detail="Positive = below target" /><Stat label="Avg episode spend" value={stats.count ? dollars(stats.average) : "—"} /><Stat label={team ? "Avg anchor spend" : "Avg target"} value={stats.count ? dollars(team ? stats.averageAnchor : stats.averageTarget) : "—"} /><Stat label={team ? "Anchor share of total spend" : "Total episode spend"} value={stats.count ? team ? `${stats.anchorShare.toFixed(1)}%` : dollars(stats.spend) : "—"} /><Stat label={team ? "Avg post-anchor spend" : "Total difference from target"} value={stats.count ? dollars(team ? stats.averagePost : stats.difference) : "—"} /></div>
    <nav aria-label="Cost dashboard views" className="flex gap-1 border-b border-slate-200">{([ ["summary", "Episode summary"], ["trends", "Episode trends"], ["episodes", "Episode details"] ] as const).map(([tab, label]) => <button key={tab} type="button" aria-current={state.tab === tab ? "page" : undefined} onClick={() => change({ costTab: tab, episode: "" })} className={`border-b-2 px-4 py-3 text-xs font-semibold ${state.tab === tab ? "border-[#207b80] text-[#176b75]" : "border-transparent text-slate-500 hover:text-slate-900"}`}>{label}</button>)}</nav>
    {episodes.length === 0 ? <div className={`${panel} py-12 text-center text-sm text-slate-500`}>No episodes match these filters. Reset filters to view the full cohort.</div> : state.tab === "summary" ? <div className="grid gap-4 xl:grid-cols-2"><CostBars title={`${team ? "Episode type" : "Condition"} · episodes by target status`} rows={groupEpisodes(episodes, "type")} kind="count" onSelect={name => filter("episodeType", name)} /><CostBars title={`${team ? "Episode type" : "Condition"} · average spend`} rows={groupEpisodes(episodes, "type")} kind="spend" onSelect={name => filter("episodeType", name)} /><CostBars title={`${team ? "Episode subtype" : "Practice"} · episodes by target status`} rows={groupEpisodes(episodes, "subtype")} kind="count" onSelect={name => filter("episodeSubtype", name)} /><CostBars title={`${team ? "Episode subtype" : "Practice"} · average spend`} rows={groupEpisodes(episodes, "subtype")} kind="spend" onSelect={name => filter("episodeSubtype", name)} /></div> : state.tab === "trends" ? <CostTrend episodes={episodes} team={team} /> : <EpisodeTable episodes={episodes} state={state} change={change} team={team} />}
    <p className="text-[11px] text-slate-500">{team ? "CMS TEAM" : "ASM"} analytics · Modeled episode data · Differences = target − spend</p>
  </div>;
}
