"use client";

import { Fragment, useState } from "react";
import type { HdiObligation, HdiObligationId } from "@/data/synthetic/healthIntelligenceObligations";
import { healthSystemSnapshot } from "@/data/synthetic/healthSystemObligations";
import { dollarAxisMaximum, nextProgramDeadline, portfolioForYear, portfolioMetricContext, portfolioMoney as money, portfolioRows, portfolioTotals, type PortfolioFilter, type PortfolioSort } from "@/lib/health-intelligence/portfolioSummary";

const fullMoney = (value: number) => value.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
const rowButton = "rounded-md px-2 py-1.5 text-xs font-semibold text-[#176b75] hover:bg-[#eaf4f1] focus-visible:outline-2 focus-visible:outline-[#176b75]";

function DollarBar({ value, maximum, opportunity = false }: { value: number; maximum: number; opportunity?: boolean }) {
  return <div className="min-w-[100px]" title={fullMoney(value)}><p className={`text-sm font-bold tabular-nums ${opportunity ? "text-[#176b75]" : "text-[#a65714]"}`}>{money(value)}</p><div className="mt-2 h-2 overflow-hidden rounded-sm bg-slate-100" aria-hidden="true"><div className={`h-full rounded-sm ${opportunity ? "bg-[#29867a]" : "bg-[#d99b59]"}`} style={{ width: `${value / maximum * 100}%` }} /></div></div>;
}

function PerformanceBullet({ program }: { program: HdiObligation }) {
  const { label, unit } = portfolioMetricContext[program.id];
  const { current, projected, target } = program.forecast;
  const suffix = unit === "%" ? "%" : " pts";
  const position = (value: number) => `${Math.max(0, Math.min(100, value))}%`;
  return <div className="min-w-[225px]"><p className="text-[11px] font-semibold text-slate-700">{label}</p><div role="img" aria-label={`${label}: current ${current}${suffix}, forecast ${projected}${suffix}, internal target ${target}${suffix}. Scale zero to 100.`} className="relative my-2 h-5"><div className="absolute inset-x-0 top-1.5 h-2 rounded-sm bg-slate-100" /><div className="absolute left-0 top-1.5 h-2 rounded-sm bg-[#d3e5e8]" style={{ width: position(projected) }} /><span className="absolute top-1 h-3 w-3 -translate-x-1/2 rounded-full border-2 border-white bg-[#236f7e] shadow-sm" style={{ left: position(current) }} /><span className="absolute top-1 h-3 w-3 -translate-x-1/2 rotate-45 border-2 border-[#236f7e] bg-white" style={{ left: position(projected) }} /><span className="absolute top-0 h-5 w-0.5 -translate-x-1/2 bg-slate-700" style={{ left: position(target) }} /></div><div className="flex items-center justify-between gap-2 text-[10px] tabular-nums text-slate-500"><span>Current <strong className="font-semibold text-slate-700">{current}{suffix}</strong></span><span>Forecast <strong className="font-semibold text-[#176b75]">{projected}{suffix}</strong></span><span>Target <strong className="font-semibold text-slate-700">{target}{suffix}</strong></span></div></div>;
}

export default function PortfolioExecutiveSummary({ onOpenProgram, onOpenWorklist }: { onOpenProgram: (id: HdiObligationId) => void; onOpenWorklist: (id: HdiObligationId) => void }) {
  const [year, setYear] = useState<"all" | "2026" | "2027">("all");
  const [filter, setFilter] = useState<PortfolioFilter>("all");
  const [sort, setSort] = useState<PortfolioSort>("opportunity");
  const [expanded, setExpanded] = useState<HdiObligationId | null>(null);
  const programs = portfolioForYear(year);
  const totals = portfolioTotals(programs);
  const rows = portfolioRows(programs, filter, sort);
  const maximum = dollarAxisMaximum(programs);
  const share = totals.risk ? totals.opportunity / totals.risk * 100 : 0;
  return <section className="space-y-4" aria-label="Portfolio executive summary">
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap items-center gap-2 text-xs text-slate-500"><span className="rounded-full bg-slate-100 px-2.5 py-1 font-semibold">Modeled estimates</span><span>{totals.count} {totals.count === 1 ? "program" : "programs"} · As of {healthSystemSnapshot.asOf}</span></div><label className="text-xs font-semibold text-slate-600">Program year<select value={year} onChange={event => { setYear(event.target.value as typeof year); setFilter("all"); setExpanded(null); }} className="ml-2 rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs"><option value="all">All · 2026 + 2027 scenario</option><option value="2026">2026</option><option value="2027">2027 · ASM scenario</option></select></label></div>
    <div className="grid gap-3 lg:grid-cols-[1fr_1fr_1.05fr]">
      <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-semibold text-slate-700">Dollars at risk</h3><span className="text-[10px] font-semibold text-slate-400">GROSS ESTIMATE</span></div><p className="mt-3 text-4xl font-bold tracking-tight tabular-nums text-[#a65714]" title={fullMoney(totals.risk)}>{money(totals.risk)}</p><p className="mt-2 text-xs text-slate-500">Across {totals.count} {totals.count === 1 ? "program" : "programs"} in scope</p><div className="mt-4 flex h-2.5 overflow-hidden rounded-sm bg-[#efdcc5]" aria-label={`${fullMoney(totals.opportunity)} recoverable within ${fullMoney(totals.risk)} at risk`} role="img"><div className="h-full bg-[#29867a]" style={{ width: `${share}%` }} /></div><p className="mt-2 text-[11px] leading-4 text-slate-500"><span className="mr-1.5 inline-block h-2 w-2 rounded-sm bg-[#29867a]" />{money(totals.opportunity)} has identified recovery opportunity</p></div>
      <div className="rounded-xl border border-[#c4ded7] bg-[#f6faf9] p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-semibold text-slate-700">Recoverable opportunity</h3><span className="text-[10px] font-semibold text-[#176b75]">WITHIN RISK</span></div><p className="mt-3 text-4xl font-bold tracking-tight tabular-nums text-[#176b75]" title={fullMoney(totals.opportunity)}>{money(totals.opportunity)}</p><p className="mt-2 text-xs text-slate-500">{share.toFixed(1)}% of {money(totals.risk)} at risk</p><p className="mt-4 text-[11px] leading-5 text-slate-600">Estimated exposure addressable through the identified program work.</p><button type="button" className={`${rowButton} -ml-2 mt-1`} onClick={() => { setSort("opportunity"); setFilter("all"); document.getElementById("portfolio-program-table")?.scrollIntoView({ behavior: "smooth", block: "start" }); }}>Rank by opportunity ↓</button></div>
      <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="text-sm font-semibold text-slate-700">Forecast below target</h3><p className="mt-3 text-4xl font-bold tracking-tight tabular-nums text-[#a65714]">{totals.forecastBelow}<span className="ml-1 text-xl font-normal text-slate-400">/ {totals.count}</span></p><p className="mt-2 text-xs text-slate-500">{totals.currentBelow} currently below their internal target</p><div className="mt-4 flex h-2.5 gap-1" aria-hidden="true">{programs.map(program => <span key={program.id} className={`h-full flex-1 rounded-sm ${program.forecast.projected < program.forecast.target ? "bg-[#d99b59]" : "bg-[#29867a]"}`} />)}</div><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-[11px]"><button type="button" className="font-semibold text-[#a65714] hover:underline" onClick={() => setFilter("below")}>{totals.forecastBelow} below forecast target</button><button type="button" className="font-semibold text-[#176b75] hover:underline" onClick={() => setFilter("meets")}>{totals.forecastMeets} forecast to meet</button></div></div>
    </div>
    <section id="portfolio-program-table" className="scroll-mt-4 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm" aria-labelledby="portfolio-performance-title">
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4"><div><h3 id="portfolio-performance-title" className="text-base font-bold text-slate-900">Obligation performance</h3><p className="mt-1 text-xs text-slate-500">{rows.length} of {totals.count} {totals.count === 1 ? "program" : "programs"} · {totals.dueSoon} work {totals.dueSoon === 1 ? "item" : "items"} due within 30 days</p></div><div className="flex flex-wrap items-center gap-3"><div className="flex gap-1 rounded-lg bg-slate-100 p-1" aria-label="Forecast filter">{([ ["all", "All"], ["below", "Below target"], ["meets", "Meets target"] ] as const).map(([value, label]) => <button key={value} type="button" aria-pressed={filter === value} onClick={() => setFilter(value)} className={`rounded-md px-3 py-1.5 text-[11px] font-semibold ${filter === value ? "bg-white text-slate-900 shadow-sm" : "text-slate-500 hover:text-slate-900"}`}>{label}</button>)}</div><label className="text-[11px] text-slate-500">Sort<select value={sort} onChange={event => setSort(event.target.value as PortfolioSort)} className="ml-2 rounded-md border border-slate-200 bg-white p-2 text-[11px] text-slate-700"><option value="opportunity">Opportunity</option><option value="risk">Dollars at risk</option><option value="deadline">Next work due</option></select></label></div></div>
      <div className="flex flex-wrap justify-between gap-2 border-b border-slate-100 bg-[#fbfcfd] px-5 py-2 text-[10px] text-slate-500"><span>Dollar bars: $0–{money(maximum)} · Same scale in both columns</span><span><span className="font-bold text-[#236f7e]">●</span> Current <span className="ml-3 font-bold text-[#236f7e]">◇</span> Forecast <span className="ml-3 font-bold text-slate-700">│</span> Internal target · Row scale 0–100</span></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[1020px] table-fixed text-left"><thead className="border-b border-slate-200 text-[10px] uppercase tracking-wide text-slate-500"><tr><th className="w-[21%] px-5 py-3">Obligation</th><th className="w-[14%] px-4 py-3">Dollars at risk</th><th className="w-[14%] px-4 py-3">Recoverable</th><th className="w-[28%] px-4 py-3">Performance</th><th className="w-[12%] px-4 py-3">Forecast gap</th><th className="w-[11%] px-4 py-3">Work due</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(program => {
        const context = portfolioMetricContext[program.id];
        const gap = program.forecast.target - program.forecast.projected;
        const due = nextProgramDeadline(program);
        return <Fragment key={program.id}><tr className="align-middle hover:bg-slate-50/70"><td className="px-5 py-4"><button type="button" onClick={() => onOpenProgram(program.id)} className="text-left text-sm font-bold text-[#176b75] hover:underline" aria-label={`Open ${program.shortTitle} overview`}>{program.shortTitle === "AMBULATORY SPECIALTY" ? "ASM" : program.shortTitle} →</button><p className="mt-1 text-[10px] text-slate-500">{context.year}{context.year === 2027 ? " · Preparation scenario" : " · Modeled program"}</p><button type="button" aria-expanded={expanded === program.id} aria-controls={expanded === program.id ? `basis-${program.id}` : undefined} onClick={() => setExpanded(expanded === program.id ? null : program.id)} className="mt-1 text-[10px] font-semibold text-slate-500 hover:text-[#176b75]">{expanded === program.id ? "−" : "+"} Basis</button></td><td className="px-4 py-4"><DollarBar value={program.atRiskDollars} maximum={maximum} /></td><td className="px-4 py-4"><DollarBar value={program.recoverableDollars} maximum={maximum} opportunity /></td><td className="px-4 py-4"><PerformanceBullet program={program} /></td><td className="px-4 py-4"><p className={`text-xs font-bold ${gap > 0 ? "text-[#a65714]" : "text-[#176b75]"}`}>{gap > 0 ? `${gap} ${context.unit === "%" ? "pp" : "pts"} below` : gap < 0 ? `${Math.abs(gap)} ${context.unit === "%" ? "pp" : "pts"} above` : "Target met"}</p><p className="mt-1 text-[10px] text-slate-500">{gap > 0 ? "Forecast shortfall" : "At forecast"}</p></td><td className="px-4 py-4">{due !== null ? <button type="button" className={`${rowButton} -ml-2 ${due <= 30 ? "!text-[#a65714]" : ""}`} onClick={() => onOpenWorklist(program.id)} aria-label={`Open ${program.shortTitle} worklist, next due in ${due} days`}>{due} days →</button> : <span className="text-xs text-slate-500">No open work</span>}<p className="text-[10px] text-slate-500">{program.workItems.length} work {program.workItems.length === 1 ? "item" : "items"}</p></td></tr>
          {expanded === program.id && <tr id={`basis-${program.id}`}><td colSpan={6} className="bg-[#f6faf9] px-5 py-4"><div className="grid gap-4 md:grid-cols-[1.2fr_1fr]"><div><h4 className="text-xs font-bold text-slate-800">{program.shortTitle} · Estimate basis</h4><p className="mt-1 text-xs leading-5 text-slate-600">{context.basis}</p><p className="mt-1 text-[11px] text-slate-500">{program.scope} · {program.deadline}</p></div><div className="text-xs leading-5 text-slate-600"><p>{fullMoney(program.recoverableDollars)} recoverable within {fullMoney(program.atRiskDollars)} at risk.</p><p>{fullMoney(program.atRiskDollars - program.recoverableDollars)} has no identified recovery in this scenario.</p><p className="mt-1 text-[11px] text-slate-500">Estimates may overlap with other programs. Work-item impacts are not added to this total.</p></div></div></td></tr>}
        </Fragment>;
      })}{!rows.length && <tr><td colSpan={6} className="px-5 py-10 text-center text-sm text-slate-500">No programs match this forecast filter.</td></tr>}</tbody></table></div>
      <div className="border-t border-slate-200 bg-[#fbfcfd] px-5 py-3 text-[11px] leading-5 text-slate-500"><p>Recoverable amounts sit within at-risk estimates. Cross-program financial overlap has not been reconciled. Performance uses each program’s own metric and internal target.</p><details className="mt-1"><summary className="cursor-pointer font-semibold text-[#176b75]">Metric definitions</summary><dl className="mt-3 grid gap-3 sm:grid-cols-3"><div><dt className="font-semibold text-slate-700">Dollars at risk</dt><dd>Program estimates of exposure if obligations are not met. The gross sum is not a reconciled expected loss.</dd></div><div><dt className="font-semibold text-slate-700">Recoverable opportunity</dt><dd>Exposure estimated to be addressable through identified work. It is not earned savings or additional revenue.</dd></div><div><dt className="font-semibold text-slate-700">Performance and gap</dt><dd>Current and forecast compared with the internal target. Gap uses points for scores and percentage points for rates. Readiness indicators are labeled separately.</dd></div></dl></details></div>
    </section>
  </section>;
}
