"use client";
import { useEffect, useState } from "react";
import type { HdiObligationId } from "@/data/synthetic/healthIntelligenceObligations";
import { programQualityResults, qualityGap, qualityPriority, qualityValue, type QualityResult } from "@/data/synthetic/programPerformance";
import PublishedMeasureRequirements from "./PublishedMeasureRequirements";

function Trend({ row }: { row: QualityResult }) {
  const low = Math.min(...row.history), high = Math.max(...row.history);
  const padding = Math.max((high - low) * .12, row.unit === "index" ? .02 : 1);
  const min = low - padding, max = high + padding;
  const y = (value: number) => 44 - (value - min) / (max - min) * 36;
  const delta = row.current - row.history[0];
  const better = row.lower ? delta < 0 : delta > 0;
  return <figure className="w-40"><svg viewBox="0 0 160 52" className="h-14 w-40" role="img" aria-label={"Apr–Sep modeled trend " + row.history.map(value => qualityValue(value, row.unit)).join(", ") + ". Internal target " + qualityValue(row.target, row.unit) + ". Zoomed scale " + qualityValue(min, row.unit) + " to " + qualityValue(max, row.unit)}><text x="0" y="9" fontSize="8" fill="#64748b">{qualityValue(max, row.unit)}</text><text x="0" y="47" fontSize="8" fill="#64748b">{qualityValue(min, row.unit)}</text>{row.target >= min && row.target <= max && <line x1="36" x2="156" y1={y(row.target)} y2={y(row.target)} stroke="#94a3b8" strokeDasharray="3 3" />}<polyline points={row.history.map((value, i) => (36 + i * 24) + "," + y(value)).join(" ")} fill="none" stroke={better ? "#16816e" : "#ad5235"} strokeWidth="2.5" /><circle cx="156" cy={y(row.current)} r="3" fill={better ? "#16816e" : "#ad5235"} /></svg><figcaption className={"text-[10px] font-semibold " + (better ? "text-emerald-700" : "text-amber-700")}>{delta > 0 ? "+" : ""}{delta.toFixed(row.unit === "index" ? 2 : 1)} {row.unit === "%" ? "pp" : "index"} · {better ? "Improving" : delta === 0 ? "Stable" : "Declining"}{(row.target < min || row.target > max) && <span className="block font-normal text-slate-500">Target {row.target > max ? "above" : "below"} plot</span>}</figcaption></figure>;
}
const providers = ["Northstar Medical Group", "Summit Family Health", "Lakeside Physicians", "Riverbend Hospital"];
export default function ProgramQualityMeasures({ programId, onOpenReporting }: { programId: HdiObligationId; onOpenReporting?: () => void }) {
  const results = programQualityResults(programId);
  const [filter, setFilter] = useState("all");
  const [sort, setSort] = useState("priority");
  const [selected, setSelected] = useState<string | null>(null);
  const [provider, setProvider] = useState("all");
  const [status, setStatus] = useState("open");
  const [reviewed, setReviewed] = useState<string[]>([]);
  const [query, setQuery] = useState("");
  useEffect(() => {
    const sync = () => { const key = new URLSearchParams(window.location.search).get("qualityMeasure"); setSelected(results.some(row => row.key === key) ? key : null); };
    sync(); window.addEventListener("popstate", sync);
    return () => window.removeEventListener("popstate", sync);
  // Stable seeded result set per program.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [programId]);
  const choose = (key: string) => {
    setSelected(key); setProvider("all"); setStatus("open"); setQuery("");
    const url = new URL(window.location.href); url.searchParams.set("qualityMeasure", key); window.history.pushState(null, "", url);
    requestAnimationFrame(() => document.getElementById("program-measure-worklist")?.scrollIntoView({ behavior: "smooth", block: "start" }));
  };
  const rows = results.filter(row => filter === "all" || (filter === "below" ? qualityGap(row) > 0 : qualityGap(row) === 0)).sort((a, b) => sort === "population" ? b.reviewCount - a.reviewCount : qualityPriority(b) - qualityPriority(a));
  const priorityKeys = [...results].sort((a, b) => qualityPriority(b) - qualityPriority(a)).map(row => row.key);
  const active = results.find(row => row.key === selected);
  const patientRows = active ? Array.from({ length: Math.min(24, active.reviewCount) }, (_, i) => {
    const id = programId.toUpperCase().slice(0, 4) + "-" + active.key + "-" + String(i + 1).padStart(4, "0");
    return { id, provider: providers[i % providers.length], reviewed: reviewed.includes(id), evidence: i % 3 === 0 ? "Evidence reconciliation" : i % 3 === 1 ? "Follow-up needed" : "Result review", due: 3 + i % 12 };
  }).filter(row => (provider === "all" || row.provider === provider) && (status === "all" || (status === "reviewed") === row.reviewed) && (row.id + " " + row.provider + " " + row.evidence).toLowerCase().includes(query.toLowerCase())) : [];
  return <section id="program-quality-measures" className="scroll-mt-5 space-y-4" aria-label="Quality performance">
    <div className="rounded-xl border border-[#b5d1ca] bg-white p-4 shadow-sm">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-bold text-slate-900">Quality measures</h3><p className="mt-1 text-xs text-slate-500">Modeled results · Internal targets · Apr–Sep trend</p></div><div className="flex flex-wrap gap-3"><label className="text-xs text-slate-600">Status<select aria-label="Quality status" className="ml-2 rounded-md border border-slate-200 p-2" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All measures</option><option value="below">Off target</option><option value="met">Target met</option></select></label><label className="text-xs text-slate-600">Sort<select aria-label="Quality sort" className="ml-2 rounded-md border border-slate-200 p-2" value={sort} onChange={e => setSort(e.target.value)}><option value="priority">Action priority</option><option value="population">Review population</option></select></label></div></div>
      <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1080px] table-fixed text-left text-xs"><thead className="border-y border-slate-100 bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th className="w-[28%] p-3">Measure</th><th className="w-[16%] p-3">Performance / target</th><th className="w-[17%] p-3">Trend</th><th className="w-[14%] p-3">Review population</th><th className="w-[25%] p-3">Next action</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(row => <tr key={row.key} className={active?.key === row.key ? "bg-[#f0f7f5]" : "hover:bg-slate-50"}><td className="p-3"><p className="mb-1 text-[10px] text-slate-500">{row.definition.id}</p><button type="button" onClick={() => choose(row.key)} className="text-left font-bold leading-5 text-[#176b75] hover:underline">{row.definition.name}</button><p className="mt-1 text-[10px] text-slate-500">{row.lower ? "Lower" : "Higher"} is better{row.key === "adult-GSD-AD" ? " · >9% poor-control rate" : ""}</p></td><td className="p-3"><p className="text-lg font-bold text-slate-900">{qualityValue(row.current, row.unit)}</p><p className="mt-1 text-slate-500">Target {row.lower ? "≤" : "≥"}{qualityValue(row.target, row.unit)}</p><p className={"mt-2 font-semibold " + (qualityGap(row) > 0 ? "text-amber-700" : "text-emerald-700")}>{qualityGap(row) > 0 ? qualityGap(row).toFixed(row.unit === "index" ? 2 : 1) + (row.unit === "%" ? " pp" : " index") + " gap" : "Target met"}</p></td><td className="p-3"><Trend row={row} /></td><td className="p-3"><p className="text-lg font-bold text-slate-900">{row.reviewCount.toLocaleString()}</p><p className="mt-1 text-[11px] text-slate-500">of {row.eligible.toLocaleString()} eligible</p><p className="mt-2 text-[10px] font-semibold text-[#176b75]">{qualityGap(row) > 0 ? "Priority " + (priorityKeys.indexOf(row.key) + 1) : "Maintain performance"}</p></td><td className="p-3"><p className="leading-5 text-slate-600">{row.action}</p><button type="button" aria-label={"Review " + row.definition.name} onClick={() => choose(row.key)} className="mt-2 rounded-md border border-[#b5d1ca] px-3 py-2 font-semibold text-[#176b75]">Review worklist →</button></td></tr>)}</tbody></table></div>
      <p className="mt-3 text-[11px] leading-5 text-slate-500">Priority uses the relative target gap and review population. Review counts are operational cohorts, not calculated numerators or guaranteed gap closures. Internal targets are not CMS benchmarks or Stars cut points. Trends use a labeled scale per measure.</p>
    </div>
    {active && <section id="program-measure-worklist" aria-label="Measure worklist" className="scroll-mt-4 rounded-xl border border-slate-200 bg-white p-5">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><h4 className="text-lg font-bold text-slate-900">{active.definition.name}</h4><p className="mt-1 text-xs text-slate-500">{active.definition.id} · {active.reviewCount.toLocaleString()} in modeled review population · {programId.toUpperCase()}</p></div><div className="flex gap-3">{onOpenReporting && <button type="button" onClick={onOpenReporting} className="text-xs font-semibold text-[#176b75]">Open MIPS dashboard →</button>}<a href={active.definition.source} target="_blank" rel="noreferrer" className="text-xs font-semibold text-[#176b75] underline">Specification ↗</a></div></div>
      <p className="mt-3 text-sm text-slate-700">{active.action}</p>
      <h5 className="mt-4 text-sm font-bold text-slate-900">Provider work</h5><div className="mt-2 grid gap-2 sm:grid-cols-4">{providers.map((name, i) => <button key={name} type="button" onClick={() => setProvider(name)} aria-pressed={provider === name} className={"rounded-lg border p-3 text-left " + (provider === name ? "border-[#28737a] bg-[#f0f7f5]" : "border-slate-200")}><p className="text-xs font-semibold text-[#176b75]">{name} →</p><p className="mt-2 text-lg font-bold">{(Math.floor(active.reviewCount / 4) + (i < active.reviewCount % 4 ? 1 : 0)).toLocaleString()} <span className="text-xs font-normal text-slate-500">to review</span></p></button>)}</div>
      <div className="mt-5 flex flex-wrap gap-3"><input aria-label="Search measure worklist" placeholder="Search record, provider, evidence" value={query} onChange={e => setQuery(e.target.value)} className="min-w-64 rounded-md border border-slate-200 p-2 text-xs" /><select aria-label="Measure worklist provider" value={provider} onChange={e => setProvider(e.target.value)} className="rounded-md border border-slate-200 p-2 text-xs"><option value="all">All providers</option>{providers.map(name => <option key={name}>{name}</option>)}</select><select aria-label="Measure review status" value={status} onChange={e => setStatus(e.target.value)} className="rounded-md border border-slate-200 p-2 text-xs"><option value="open">Open review</option><option value="reviewed">Reviewed</option><option value="all">All records</option></select></div>
      <p className="my-3 text-xs text-slate-500">{patientRows.length} illustrative {patientRows.length === 1 ? "record" : "records"} shown · Sample of the selected measure’s review population</p>
      <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{["Record", "Provider", "Evidence", "Due", "Action"].map(label => <th className="p-2" key={label}>{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{patientRows.map(row => <tr key={row.id}><td className="p-2 font-semibold">{row.id}</td><td className="p-2">{row.provider}</td><td className="p-2">{row.evidence}</td><td className="p-2">{row.due} days</td><td className="p-2"><button type="button" onClick={() => setReviewed(old => row.reviewed ? old.filter(id => id !== row.id) : [...old, row.id])} className="font-semibold text-[#176b75]">{row.reviewed ? "Reopen review" : "Mark reviewed"}</button></td></tr>)}{!patientRows.length && <tr><td colSpan={5} className="p-4 text-slate-500">No records match these filters.</td></tr>}</tbody></table></div><p className="mt-3 text-[11px] text-slate-500">Review status is local to this demo and does not change the measure result.</p>
    </section>}
    <details className="rounded-xl border border-slate-200 bg-white p-4"><summary className="cursor-pointer text-xs font-semibold text-[#176b75]">Published requirements and sources</summary><div className="mt-4"><PublishedMeasureRequirements programId={programId} idPrefix="published-quality" /></div></details>
  </section>;
}
