"use client";

import {
  type HdiCrossProgramOpportunity,
  type HdiObligation,
  type HdiObligationId,
} from "@/data/synthetic/healthIntelligenceObligations";
import VbcContractPortfolio from "@/components/health-intelligence/VbcContractPortfolio";

const money = (value: number) => value >= 1_000_000 ? `$${(value / 1_000_000).toFixed(1)}M` : `$${Math.round(value / 1_000)}K`;
const whole = (value: number) => value.toLocaleString("en-US");

function TrendChart({ obligation }: { obligation: HdiObligation }) {
  const width = 560;
  const height = 168;
  const delta = obligation.forecast.projected - obligation.forecast.current;
  const values = [obligation.forecast.current - Math.round(delta * 0.7), obligation.forecast.current - Math.round(delta * 0.4), obligation.forecast.current - Math.round(delta * 0.2), obligation.forecast.current, obligation.forecast.current + Math.round(delta * 0.55), obligation.forecast.projected];
  const all = [...values, obligation.forecast.target];
  const min = Math.min(...all) - 1;
  const max = Math.max(...all) + 1;
  const y = (value: number) => height - 28 - ((value - min) / Math.max(1, max - min)) * (height - 52);
  const x = (index: number) => 36 + (index / (values.length - 1)) * (width - 56);
  const points = values.map((value, index) => `${x(index)},${y(value)}`).join(" ");
  return <div className="rounded-xl border border-[#e2e7ee] bg-white p-4 shadow-sm">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.13em] text-[#28737a]">Performance trend</p><h3 className="mt-1 text-base font-bold tracking-tight text-slate-900">{obligation.forecast.unit} trajectory</h3><p className="mt-1 text-[11px] text-slate-500">Current, projected, and target across the latest refreshes.</p></div><span className="text-[11px] font-semibold text-slate-500">Target {obligation.forecast.target}{obligation.forecast.unit.includes("%") ? "%" : ""}</span></div>
    <svg className="mt-3 h-40 w-full" viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${obligation.title} performance trajectory`}>
      {[0, 1, 2].map((index) => { const lineY = 20 + index * 52; return <line key={lineY} x1="36" x2={width - 20} y1={lineY} y2={lineY} stroke="#e8edf2" strokeDasharray="3 4" />; })}
      <line x1="36" x2={width - 20} y1={y(obligation.forecast.target)} y2={y(obligation.forecast.target)} stroke="#2d8a78" strokeDasharray="5 4" strokeWidth="1.5" />
      <polyline points={points} fill="none" stroke="#5270e8" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" />
      {values.map((value, index) => <circle key={`${value}-${index}`} cx={x(index)} cy={y(value)} r={index === values.length - 1 ? 5 : 3.5} fill="#5270e8" stroke="white" strokeWidth="1.5" />)}
      <text x="40" y="14" fill="#94a3b8" fontSize="10">{Math.round(max)}{obligation.forecast.unit.includes("%") ? "%" : ""}</text>
      <text x="40" y={height - 30} fill="#94a3b8" fontSize="10">{Math.round(min)}{obligation.forecast.unit.includes("%") ? "%" : ""}</text>
      {['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'].map((label, index) => <text key={label} x={x(index)} y={height - 8} textAnchor="middle" fill="#94a3b8" fontSize="10">{label}</text>)}
    </svg>
    <div className="flex flex-wrap items-center gap-4 border-t border-slate-100 pt-2 text-[10px] font-semibold text-slate-500"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#5270e8]" />Forecast trajectory</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#2d8a78]" />Target baseline</span></div>
  </div>;
}

function ValueCapture({ obligation }: { obligation: HdiObligation }) {
  const protectedValue = Math.max(0, obligation.atRiskDollars - obligation.recoverableDollars);
  const capture = Math.round((protectedValue / Math.max(1, obligation.atRiskDollars)) * 100);
  return <section className="rounded-xl border border-[#e2e7ee] bg-white p-4 shadow-sm">
    <p className="text-[10px] font-bold uppercase tracking-[0.13em] text-[#28737a]">Value position</p><h3 className="mt-1 text-base font-bold tracking-tight text-slate-900">What is already protected vs. still open</h3>
    <div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-lg bg-[#e8f3ef] p-3"><p className="text-[10px] font-bold uppercase tracking-wide text-[#28737a]">Protected value</p><p className="mt-1 text-xl font-bold text-emerald-700">{money(protectedValue)}</p><p className="mt-1 text-[10px] text-slate-500">{capture}% of modeled risk</p></div><div className="rounded-lg bg-[#fff6e7] p-3"><p className="text-[10px] font-bold uppercase tracking-wide text-[#b85d12]">Remaining opportunity</p><p className="mt-1 text-xl font-bold text-amber-700">{money(obligation.recoverableDollars)}</p><p className="mt-1 text-[10px] text-slate-500">Open work across {obligation.workItems.length} queues</p></div></div>
    <div className="mt-4"><div className="flex items-center justify-between text-[10px] font-bold uppercase tracking-wide text-slate-400"><span>Value capture</span><span>{capture}%</span></div><div className="mt-1.5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-[#36b98a] to-[#0f8061]" style={{ width: `${capture}%` }} /></div></div>
    <div className="mt-4 grid grid-cols-3 gap-2 border-t border-slate-100 pt-3 text-center"><div><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Lives</p><p className="mt-1 text-sm font-bold text-slate-900">{whole(obligation.lives)}</p></div><div><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Providers</p><p className="mt-1 text-sm font-bold text-slate-900">{whole(obligation.providers)}</p></div><div><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Due</p><p className="mt-1 text-sm font-bold text-red-700">{Math.min(...obligation.workItems.map((item) => item.dueInDays))}d</p></div></div>
  </section>;
}

function DriverTable({ obligation, onOpenPatientWorklist }: { obligation: HdiObligation; onOpenPatientWorklist: (measure: string) => void }) {
  return <section className="rounded-xl border border-[#e2e7ee] bg-white p-4 shadow-sm"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.13em] text-[#28737a]">Measure and work drivers</p><h3 className="mt-1 text-base font-bold tracking-tight text-slate-900">The work that moves this obligation</h3></div><span className="text-[10px] font-semibold text-slate-500">Select a driver to open patients</span></div><div className="mt-3 overflow-x-auto"><div className="min-w-[700px]"><div className="grid grid-cols-[minmax(190px,1.4fr)_minmax(160px,1fr)_110px_90px_120px] gap-3 border-b border-slate-100 pb-2 text-[10px] font-bold uppercase tracking-wide text-slate-400"><span>Driver</span><span>Practice / owner</span><span>Impact</span><span>Due</span><span>Next view</span></div><div className="divide-y divide-slate-100">{obligation.workItems.map((item) => <div key={item.id} className="grid grid-cols-[minmax(190px,1.4fr)_minmax(160px,1fr)_110px_90px_120px] items-center gap-3 py-3"><div><button type="button" onClick={() => onOpenPatientWorklist(item.driver)} className="text-left text-xs font-bold text-[#176b75] hover:underline">{item.driver} ↗</button><p className="mt-1 text-[10px] leading-4 text-slate-500">{item.evidence}</p></div><div><p className="text-xs font-semibold text-slate-700">{item.practice}</p><p className="mt-1 text-[10px] text-slate-500">{item.owner}</p></div><p className="text-xs font-bold text-emerald-700">{money(item.impact)}</p><p className={`text-xs font-semibold ${item.dueInDays <= 21 ? "text-red-700" : "text-slate-600"}`}>{item.dueInDays}d</p><button type="button" onClick={() => onOpenPatientWorklist(item.driver)} className="rounded-lg border border-[#b5d1ca] bg-[#f5fbf8] px-2.5 py-1.5 text-[10px] font-semibold text-[#285954] hover:bg-[#e8f3ef]">Open patients</button></div>)}</div></div></div></section>;
}

export default function ProgramOverview({ obligation, opportunities, onBack, onWorklist, onOpenDataSubmissions, onOpenPatientWorklist, onOpenContract }: { obligation: HdiObligation; opportunities: HdiCrossProgramOpportunity[]; onBack: () => void; onWorklist: (id: HdiObligationId) => void; onOpenDataSubmissions?: () => void; onOpenPatientWorklist: (measure: string) => void; onOpenContract?: (contractId: string) => void }) {
  if (obligation.id === "vbc-contracts") {
    return <VbcContractPortfolio obligation={obligation} onBack={onBack} onOpenPatientWorklist={onOpenPatientWorklist} onOpenContract={onOpenContract ?? (() => undefined)} />;
  }
  const protectedValue = Math.max(0, obligation.atRiskDollars - obligation.recoverableDollars);
  const capture = Math.round((protectedValue / Math.max(1, obligation.atRiskDollars)) * 100);
  return <section className="space-y-4">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#28737a]">Program overview</p><h2 className="mt-1 text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl">{obligation.title}</h2><p className="mt-1 text-xs text-slate-500">{obligation.category} · {obligation.scope} · {obligation.deadline}</p></div><button type="button" onClick={onBack} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50">← Back to portfolio</button></div>
    <section className="rounded-xl border border-[#e2e7ee] bg-white p-4 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><span className="rounded-full bg-[#e8f3ef] px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide text-[#285954]">{obligation.shortTitle}</span><span className="text-[11px] font-semibold text-slate-500">{obligation.sponsor}</span></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${obligation.forecast.projected >= obligation.forecast.target ? "bg-[#e8f3ef] text-[#285954]" : "bg-[#fff6e7] text-[#9b641d]"}`}>{obligation.forecast.projected >= obligation.forecast.target ? "Target met" : `${obligation.forecast.target - obligation.forecast.projected} pt gap`}</span></div><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4"><div><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Attributed lives</p><p className="mt-1 text-xl font-bold text-slate-900">{whole(obligation.lives)}</p><p className="mt-1 text-[10px] text-slate-500">{whole(obligation.providers)} providers / participants</p></div><div><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Projected score</p><p className="mt-1 text-xl font-bold text-[#5270e8]">{obligation.forecast.projected}{obligation.forecast.unit.includes("%") ? "%" : ""}</p><p className="mt-1 text-[10px] text-slate-500">Target {obligation.forecast.target}{obligation.forecast.unit.includes("%") ? "%" : ""}</p></div><div><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Protected value</p><p className="mt-1 text-xl font-bold text-emerald-700">{money(protectedValue)}</p><p className="mt-1 text-[10px] text-slate-500">{capture}% of risk positioned</p></div><div><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Remaining opportunity</p><p className="mt-1 text-xl font-bold text-amber-700">{money(obligation.recoverableDollars)}</p><p className="mt-1 text-[10px] text-slate-500">Across {obligation.workItems.length} work queues</p></div></div></section>
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1.18fr)_minmax(340px,0.82fr)]"><TrendChart obligation={obligation} /><ValueCapture obligation={obligation} /></div>
    <DriverTable obligation={obligation} onOpenPatientWorklist={onOpenPatientWorklist} />
    <details className="rounded-xl border border-[#dbe9e4] bg-[#f8fbfa] p-4"><summary className="flex cursor-pointer items-center justify-between gap-3 text-sm font-bold text-slate-900"><span>Open full obligation detail</span><span className="text-xs font-semibold text-[#176b75]">{opportunities.length} shared pathways · {obligation.forecast.unit}</span></summary><div className="mt-4 grid gap-3 border-t border-[#dbe9e4] pt-4 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Sponsor</p><p className="mt-1 text-sm font-semibold text-slate-800">{obligation.sponsor}</p></div><div><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Scope</p><p className="mt-1 text-sm font-semibold text-slate-800">{obligation.scope}</p></div><div><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Forecast now</p><p className="mt-1 text-sm font-semibold text-slate-800">{obligation.forecast.current} → {obligation.forecast.projected}</p></div><div><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Next deadline</p><p className="mt-1 text-sm font-semibold text-slate-800">{obligation.deadline}</p></div></div><div className="mt-4 flex flex-wrap gap-2">{opportunities.flatMap((opportunity) => opportunity.measureSet.slice(0, 2)).map((measure) => <button key={measure} type="button" onClick={() => onOpenPatientWorklist(measure)} className="rounded-lg bg-white px-2.5 py-1.5 text-[11px] font-semibold text-[#176b75] ring-1 ring-[#b5d1ca] hover:bg-[#e8f3ef]">{measure} ↗</button>)}</div><button type="button" onClick={() => obligation.id === "mips-mvp" && onOpenDataSubmissions ? onOpenDataSubmissions() : onWorklist(obligation.id)} className="mt-4 rounded-lg bg-[#285954] px-3 py-2 text-xs font-semibold text-white hover:bg-[#1f4b47]">{obligation.id === "mips-mvp" ? "Open MIPS performance dashboard" : "Open coordinated worklist"} →</button></details>
  </section>;
}
