import { chromium, firefox, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
const base = process.env.BASE_URL || 'http://127.0.0.1:3000';
const browserType = process.env.BROWSER === 'firefox' ? firefox : chromium;
const browser = await browserType.launch(process.env.BROWSER !== 'firefox' && process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {});
const context = await browser.newContext({ viewport: { width: 1440, height: 1050 } });
const page = await context.newPage();
const errors = [];
page.on('pageerror', e => errors.push(e.message));
const screenshotDir = new URL('../docs/screenshots/', import.meta.url);
await mkdir(screenshotDir, { recursive: true });
const shot = name => page.screenshot({ path: new URL(name, screenshotDir).pathname, fullPage: false });
try {
  await page.goto(base);
  const initialDs = page.frameLocator('iframe[title="Data Submissions"]');
  await expect(initialDs.locator('#labModeSelect')).toBeVisible();
  await initialDs.locator('#labModeSelect').selectOption('pm-sandbox');
  await expect(page.getByLabel('Select product', { exact: true })).toHaveValue('pm-sandbox');
  await page.getByLabel('Select product', { exact: true }).selectOption('data-submissions');
  await expect(initialDs.locator('#labModeSelect')).toHaveValue('vision');
  await initialDs.locator('#labModeSelect').selectOption('production');
  await expect(initialDs.locator('#programSelect')).toBeVisible();
  await expect(page.locator('.union-bar')).toBeHidden();
  for (const program of ['MIPS', 'MVP', 'APPPLUS', 'QRDA']) {
    await initialDs.locator('#programSelect').selectOption(program);
    await expect(initialDs.locator('#programSelect')).toHaveValue(program);
  }
  await initialDs.locator('#programSelect').selectOption('pm-sandbox');
  await expect(page.getByLabel('Select product', { exact: true })).toHaveValue('pm-sandbox');
  await page.getByLabel('Select product', { exact: true }).selectOption('data-submissions');
  await expect(initialDs.locator('#programSelect')).toHaveValue('QRDA');
  await page.goBack();
  await expect(page.getByLabel('Select product', { exact: true })).toHaveValue('pm-sandbox');
  await page.goForward();
  await expect(initialDs.locator('#programSelect')).toHaveValue('QRDA');
  await page.goto(`${base}/contracts/mssp-001`);
  await expect(page.getByRole('button', { name: 'Open Scenario Studio', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Open Scenario Studio', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await shot('01-pm-sandbox.png');
  const navigationCount = await page.evaluate(() => performance.getEntriesByType('navigation').length);
  await page.getByLabel('Select product', { exact: true }).selectOption('data-submissions');
  const ds = page.frameLocator('iframe[title="Data Submissions"]');
  await ds.locator('#scenarioSelect').selectOption('appplus-score');
  await expect(ds.locator('#scenarioSelect')).toHaveValue('appplus-score');
  await shot('02-data-submissions.png');
  await ds.getByRole('button', { name: 'Shared design criteria', exact: true }).click();
  await page.getByRole('button', { name: 'Pull all 7 criteria' }).click();
  await expect(page.locator('.union-record')).toHaveCount(7);
  await page.getByLabel('Source product', { exact: true }).selectOption('data-submissions');
  await page.getByRole('button', { name: 'Pull all 6 criteria' }).click();
  await expect(page.locator('.union-record')).toHaveCount(13);
  let criterion = page.locator('.union-record').filter({ has: page.getByRole('heading', { name: 'APP Plus APM Entity Score', exact: true }) });
  await criterion.getByRole('button', { name: 'Refine', exact: true }).click();
  await page.getByLabel('Title', { exact: true }).fill('APP Plus shared review');
  await page.getByLabel('Acceptance criteria', { exact: true }).fill('Keep APM entity context visible in both products.');
  await page.getByRole('button', { name: 'Save shared criterion' }).click();
  await expect(page.getByRole('heading', { name: 'APP Plus shared review', exact: true })).toBeVisible();
  await page.getByLabel('Select product', { exact: true }).selectOption('pm-sandbox');
  await page.getByLabel('Show', { exact: true }).selectOption('all');
  criterion = page.locator('.union-record').filter({ has: page.getByRole('heading', { name: 'APP Plus shared review', exact: true }) });
  await criterion.getByRole('button', { name: 'Use in PM Sandbox', exact: true }).click();
  await expect(criterion.getByText('Used in: Data Submissions + PM Sandbox', { exact: true })).toBeVisible();
  await criterion.getByRole('button', { name: 'Refine', exact: true }).click();
  await page.getByLabel('Design requirement', { exact: true }).fill('Refined from PM Sandbox with the submission scope intact.');
  await page.getByRole('button', { name: 'Save shared criterion' }).click();
  await page.getByRole('button', { name: 'Pull all 6 criteria' }).click();
  await expect(page.locator('.union-record')).toHaveCount(13);
  await expect(criterion.getByText('Refined from PM Sandbox with the submission scope intact.', { exact: true }).first()).toBeVisible();
  await page.getByLabel('Select product', { exact: true }).selectOption('data-submissions');
  await expect(criterion.getByText('Refined from PM Sandbox with the submission scope intact.', { exact: true }).first()).toBeVisible();
  await shot('03-shared-criteria.png');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export library', exact: true }).click();
  const download = await downloadPromise;
  const filePath = await download.path();
  await page.getByLabel('Import criteria JSON').setInputFiles(filePath);
  await expect(page.getByRole('status').filter({ hasText: '0 added; 13 unchanged.' })).toBeVisible();
  await page.getByRole('button', { name: 'Return to Data Submissions', exact: true }).click();
  await expect(ds.locator('#scenarioSelect')).toHaveValue('appplus-score');
  await ds.locator('#labModeSelect').selectOption('pm-sandbox');
  await expect(page.getByRole('button', { name: 'Open Scenario Studio', exact: true })).toBeVisible();
  expect(new URL(page.url()).pathname).toBe('/contracts/mssp-001');
  expect(await page.evaluate(() => performance.getEntriesByType('navigation').length)).toBe(navigationCount);
  await page.reload();
  await page.getByRole('button', { name: 'Design criteria', exact: true }).click();
  await expect(page.locator('.union-record')).toHaveCount(13);
  // A second tab edits the same database; the first receives the update without refresh.
  const other = await context.newPage();
  await other.goto(`${base}/?product=data-submissions`);
  await other.frameLocator('iframe[title="Data Submissions"]').getByRole('button', { name: 'Shared design criteria', exact: true }).click();
  const otherCriterion = other.locator('.union-record').filter({ has: other.getByRole('heading', { name: 'APP Plus shared review', exact: true }) });
  await otherCriterion.getByRole('button', { name: 'Refine', exact: true }).click();
  await other.getByLabel('Title', { exact: true }).fill('Cross-tab shared review');
  await other.getByRole('button', { name: 'Save shared criterion' }).click();
  await expect(page.getByRole('heading', { name: 'Cross-tab shared review', exact: true })).toBeVisible();
  await other.close();
  for (const route of ['/scorecards', '/contracts', '/cohorts', '/projects']) {
    const response = await page.goto(`${base}${route}`); expect(response?.status()).toBe(200);
    await expect(page.getByLabel('Select product', { exact: true })).toHaveValue('pm-sandbox');
  }
  await page.goto(`${base}/scorecards/contract/mssp-001`);
  await expect(page).toHaveURL(/\/contracts\/mssp-001\/scorecard/);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Design criteria', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Design criteria', exact: true })).toBeVisible();
  await shot('04-mobile-criteria.png');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(errors).toEqual([]);
  console.log('PASS: product switching, preserved state, scenario studio, bidirectional criteria refinement, deduplication, export/import, reload persistence, cross-tab updates, existing routes, legacy redirect, mobile layout, no page errors.');
} finally { await browser.close(); }
